update(doc): flesh out and add authors
chingu-voyage7/Bears-Team-17 pull request #1
Opened 2018-11-25 21:18 UTC by nikrb

Initially I added slack id's, names and github profiles, but then thought you might not want that, so please add what detail you want about yourselves.

2018-11-25 21:39 UTC, unrealkaii commented on README.md
> +* **kofi** -
I would love us to use our github usernames, apart from that. great start 👍

2018-11-25 21:40 UTC, unrealkaii requested changes
I would prefer using my github username only. apart from that. Great to start !

2018-11-26 00:30 UTC, unrealkaii commented on README.md
> +* **kofi** -
```suggestion
* **kofi** - [@unrealkaii](https://github.com/unrealkaii)
```

2018-11-27 12:45 UTC, nikrb commented
@unrealkaii the review is preventing this being merged. I thought commit the suggestion would give us green lights, not sure why it hasn't. Can you approve this so I can merge it?

2018-11-27 12:53 UTC, unrealkaii approved these changes

2018-11-27 12:58 UTC, Francis-Njoku approved these changes

2018-11-28 01:11 UTC, merged