Feature add api post question
chingu-voyage7/Bears-Team-17 pull request #13
Opened 2018-12-19 11:58 UTC by psitronic

A REST API to post/add question:
- link /api/postQuestion
- all arguments in the request body as:
key: question
value: {"messageText":"Empty",
            "messageTitle":"Hi",
            "messageTags":[],
            "messageAuthor":"5c0108713d25cfdde5a5a4b3"}

where Author is the ObjectID
- if a question posted successfully:
{
    "success": true,
    "message": "Question posted"
}

2018-12-19 20:21 UTC, nikrb requested changes
works for me.

2018-12-19 20:21 UTC, nikrb commented on server/routes/api.js
> +          message: 'Question posted'
I think we should pass the new question _id aswell

2018-12-19 20:21 UTC, nikrb commented on server/routes/api.js
> +api.post('/postQuestion', (req, res) => {
I think route should be just `/question`

2018-12-20 07:35 UTC, psitronic commented on server/routes/api.js
> +          message: 'Question posted'
Thanks for pointing it out. Actually I wanted to return an entire posted document. Now it is fixed

2018-12-20 07:37 UTC, psitronic commented on server/routes/api.js
> +api.post('/postQuestion', (req, res) => {
I am not sure, because we also need to get question(s) from the DB, so there should be many routes.

2018-12-20 07:46 UTC, Francis-Njoku submitted a review, later dismissed

2018-12-20 13:51 UTC, nikrb commented on server/routes/api.js
> +api.post('/postQuestion', (req, res) => {
yes, but the requests to question should be `/question`, whether they be get, put, post, delete etc. Atleast that's what I understand by a loosely REST based approach.
Can you give an example of why you would call them e.g. `/postQuestion`, `getQuestion`. Maybe I have the wrong end of the stick?

2018-12-20 13:57 UTC, psitronic commented on server/routes/api.js
> +api.post('/postQuestion', (req, res) => {
Technically, it is ok to use the same `/question` for `get` and `post`, but it is then not clear what exactly it does when you see `/question` get request. Does it request one last question, any question, all questions, etc.? It is just for convenience... However, I am fine with `/question` as well, at least at the moment.

2018-12-20 13:59 UTC, psitronic commented on server/routes/api.js
> +api.post('/postQuestion', (req, res) => {
Fixed

2018-12-20 15:23 UTC, nikrb commented on server/routes/api.js
> +    const parsedQuestion = JSON.parse(req.body.question);
sorry forgot to mention this breaks my test, so have removed it locally. I think this is done by the body parser. How are you testing the route locally?

2018-12-20 15:25 UTC, psitronic commented on server/routes/api.js
> +    const parsedQuestion = JSON.parse(req.body.question);
I use Postman

2018-12-20 17:12 UTC, nikrb commented on server/routes/api.js
> +    const parsedQuestion = JSON.parse(req.body.question);
ok fair enough. I take it the parse was necessary. Interesting I breaks a request from front end. Let's leave it for now and see how things go.

2018-12-20 17:18 UTC, nikrb commented
@psitronic sorry dude one last thing and I think we're good to go.
linter objects to db definition in api.js:
```
/home/nik/projects/chingu/voyage7/bears17/server/routes/api.js
  3:7  error  'db' is assigned a value but never used  no-unused-vars
```

2018-12-20 17:53 UTC, psitronic commented
> @psitronic sorry dude one last thing and I think we're good to go.
> linter objects to db definition in api.js:
> 
> ```
> /home/nik/projects/chingu/voyage7/bears17/server/routes/api.js
>   3:7  error  'db' is assigned a value but never used  no-unused-vars
> ```

I need to execute the code in db.js in order to connect the DB. Of course it could be done in the api.js or even index.js file but I think it should be in the different file.

2018-12-20 18:19 UTC, psitronic commented
Now I move the DB connection to index.js. It perhaps looks more logical.

2018-12-20 22:40 UTC, nikrb commented
@psitronic so sorry dude, messed you about a treat there, many apologies.
I think it's a better idea to have the db conn in a different file, as you said. When I ran it locally, I just removed that db import in index.js and it still worked, hence my comment it could be removed. I didn't intend for 'everything' to be moved into index.js.

I think it's best to leave it as is for now and we can move it around if need be later.

2018-12-20 22:41 UTC, nikrb approved these changes

2018-12-21 16:58 UTC, merged